/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-11-30 at 07:20:27 UTC 
 * Modify at your own risk.
 */

package com.soph1her.toycollectioncrazyscarygirledition.toyendpoint;

/**
 * Service definition for Toyendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ToyendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Toyendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the toyendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://rising-solstice-388.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "toyendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Toyendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Toyendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getToy".
   *
   * This request holds the parameters needed by the the toyendpoint server.  After setting any
   * optional parameters, call the {@link GetToy#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetToy getToy(java.lang.String id) throws java.io.IOException {
    GetToy result = new GetToy(id);
    initialize(result);
    return result;
  }

  public class GetToy extends ToyendpointRequest<com.soph1her.toycollectioncrazyscarygirledition.toyendpoint.model.Toy> {

    private static final String REST_PATH = "toy/{id}";

    /**
     * Create a request for the method "getToy".
     *
     * This request holds the parameters needed by the the toyendpoint server.  After setting any
     * optional parameters, call the {@link GetToy#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetToy#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetToy(java.lang.String id) {
      super(Toyendpoint.this, "GET", REST_PATH, null, com.soph1her.toycollectioncrazyscarygirledition.toyendpoint.model.Toy.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetToy setAlt(java.lang.String alt) {
      return (GetToy) super.setAlt(alt);
    }

    @Override
    public GetToy setFields(java.lang.String fields) {
      return (GetToy) super.setFields(fields);
    }

    @Override
    public GetToy setKey(java.lang.String key) {
      return (GetToy) super.setKey(key);
    }

    @Override
    public GetToy setOauthToken(java.lang.String oauthToken) {
      return (GetToy) super.setOauthToken(oauthToken);
    }

    @Override
    public GetToy setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetToy) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetToy setQuotaUser(java.lang.String quotaUser) {
      return (GetToy) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetToy setUserIp(java.lang.String userIp) {
      return (GetToy) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetToy setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetToy set(String parameterName, Object value) {
      return (GetToy) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertToy".
   *
   * This request holds the parameters needed by the the toyendpoint server.  After setting any
   * optional parameters, call the {@link InsertToy#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.soph1her.toycollectioncrazyscarygirledition.toyendpoint.model.Toy}
   * @return the request
   */
  public InsertToy insertToy(com.soph1her.toycollectioncrazyscarygirledition.toyendpoint.model.Toy content) throws java.io.IOException {
    InsertToy result = new InsertToy(content);
    initialize(result);
    return result;
  }

  public class InsertToy extends ToyendpointRequest<com.soph1her.toycollectioncrazyscarygirledition.toyendpoint.model.Toy> {

    private static final String REST_PATH = "toy";

    /**
     * Create a request for the method "insertToy".
     *
     * This request holds the parameters needed by the the toyendpoint server.  After setting any
     * optional parameters, call the {@link InsertToy#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertToy#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.soph1her.toycollectioncrazyscarygirledition.toyendpoint.model.Toy}
     * @since 1.13
     */
    protected InsertToy(com.soph1her.toycollectioncrazyscarygirledition.toyendpoint.model.Toy content) {
      super(Toyendpoint.this, "POST", REST_PATH, content, com.soph1her.toycollectioncrazyscarygirledition.toyendpoint.model.Toy.class);
    }

    @Override
    public InsertToy setAlt(java.lang.String alt) {
      return (InsertToy) super.setAlt(alt);
    }

    @Override
    public InsertToy setFields(java.lang.String fields) {
      return (InsertToy) super.setFields(fields);
    }

    @Override
    public InsertToy setKey(java.lang.String key) {
      return (InsertToy) super.setKey(key);
    }

    @Override
    public InsertToy setOauthToken(java.lang.String oauthToken) {
      return (InsertToy) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertToy setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertToy) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertToy setQuotaUser(java.lang.String quotaUser) {
      return (InsertToy) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertToy setUserIp(java.lang.String userIp) {
      return (InsertToy) super.setUserIp(userIp);
    }

    @Override
    public InsertToy set(String parameterName, Object value) {
      return (InsertToy) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listToy".
   *
   * This request holds the parameters needed by the the toyendpoint server.  After setting any
   * optional parameters, call the {@link ListToy#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListToy listToy() throws java.io.IOException {
    ListToy result = new ListToy();
    initialize(result);
    return result;
  }

  public class ListToy extends ToyendpointRequest<com.soph1her.toycollectioncrazyscarygirledition.toyendpoint.model.CollectionResponseToy> {

    private static final String REST_PATH = "toy";

    /**
     * Create a request for the method "listToy".
     *
     * This request holds the parameters needed by the the toyendpoint server.  After setting any
     * optional parameters, call the {@link ListToy#execute()} method to invoke the remote operation.
     * <p> {@link
     * ListToy#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListToy() {
      super(Toyendpoint.this, "GET", REST_PATH, null, com.soph1her.toycollectioncrazyscarygirledition.toyendpoint.model.CollectionResponseToy.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListToy setAlt(java.lang.String alt) {
      return (ListToy) super.setAlt(alt);
    }

    @Override
    public ListToy setFields(java.lang.String fields) {
      return (ListToy) super.setFields(fields);
    }

    @Override
    public ListToy setKey(java.lang.String key) {
      return (ListToy) super.setKey(key);
    }

    @Override
    public ListToy setOauthToken(java.lang.String oauthToken) {
      return (ListToy) super.setOauthToken(oauthToken);
    }

    @Override
    public ListToy setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListToy) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListToy setQuotaUser(java.lang.String quotaUser) {
      return (ListToy) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListToy setUserIp(java.lang.String userIp) {
      return (ListToy) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListToy setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListToy setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListToy set(String parameterName, Object value) {
      return (ListToy) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeToy".
   *
   * This request holds the parameters needed by the the toyendpoint server.  After setting any
   * optional parameters, call the {@link RemoveToy#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveToy removeToy(java.lang.String id) throws java.io.IOException {
    RemoveToy result = new RemoveToy(id);
    initialize(result);
    return result;
  }

  public class RemoveToy extends ToyendpointRequest<Void> {

    private static final String REST_PATH = "toy/{id}";

    /**
     * Create a request for the method "removeToy".
     *
     * This request holds the parameters needed by the the toyendpoint server.  After setting any
     * optional parameters, call the {@link RemoveToy#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveToy#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveToy(java.lang.String id) {
      super(Toyendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveToy setAlt(java.lang.String alt) {
      return (RemoveToy) super.setAlt(alt);
    }

    @Override
    public RemoveToy setFields(java.lang.String fields) {
      return (RemoveToy) super.setFields(fields);
    }

    @Override
    public RemoveToy setKey(java.lang.String key) {
      return (RemoveToy) super.setKey(key);
    }

    @Override
    public RemoveToy setOauthToken(java.lang.String oauthToken) {
      return (RemoveToy) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveToy setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveToy) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveToy setQuotaUser(java.lang.String quotaUser) {
      return (RemoveToy) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveToy setUserIp(java.lang.String userIp) {
      return (RemoveToy) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveToy setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveToy set(String parameterName, Object value) {
      return (RemoveToy) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateToy".
   *
   * This request holds the parameters needed by the the toyendpoint server.  After setting any
   * optional parameters, call the {@link UpdateToy#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.soph1her.toycollectioncrazyscarygirledition.toyendpoint.model.Toy}
   * @return the request
   */
  public UpdateToy updateToy(com.soph1her.toycollectioncrazyscarygirledition.toyendpoint.model.Toy content) throws java.io.IOException {
    UpdateToy result = new UpdateToy(content);
    initialize(result);
    return result;
  }

  public class UpdateToy extends ToyendpointRequest<com.soph1her.toycollectioncrazyscarygirledition.toyendpoint.model.Toy> {

    private static final String REST_PATH = "toy";

    /**
     * Create a request for the method "updateToy".
     *
     * This request holds the parameters needed by the the toyendpoint server.  After setting any
     * optional parameters, call the {@link UpdateToy#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateToy#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.soph1her.toycollectioncrazyscarygirledition.toyendpoint.model.Toy}
     * @since 1.13
     */
    protected UpdateToy(com.soph1her.toycollectioncrazyscarygirledition.toyendpoint.model.Toy content) {
      super(Toyendpoint.this, "PUT", REST_PATH, content, com.soph1her.toycollectioncrazyscarygirledition.toyendpoint.model.Toy.class);
    }

    @Override
    public UpdateToy setAlt(java.lang.String alt) {
      return (UpdateToy) super.setAlt(alt);
    }

    @Override
    public UpdateToy setFields(java.lang.String fields) {
      return (UpdateToy) super.setFields(fields);
    }

    @Override
    public UpdateToy setKey(java.lang.String key) {
      return (UpdateToy) super.setKey(key);
    }

    @Override
    public UpdateToy setOauthToken(java.lang.String oauthToken) {
      return (UpdateToy) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateToy setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateToy) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateToy setQuotaUser(java.lang.String quotaUser) {
      return (UpdateToy) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateToy setUserIp(java.lang.String userIp) {
      return (UpdateToy) super.setUserIp(userIp);
    }

    @Override
    public UpdateToy set(String parameterName, Object value) {
      return (UpdateToy) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Toyendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Toyendpoint}. */
    @Override
    public Toyendpoint build() {
      return new Toyendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ToyendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setToyendpointRequestInitializer(
        ToyendpointRequestInitializer toyendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(toyendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
